export const PROJECT_LIST_FETCH_REQUESTED = 'PROJECT_LIST_FETCH_REQUESTED';
export const PROJECT_LIST_FETCH_SUCCEEDED = 'PROJECT_LIST_FETCH_SUCCEEDED';
export const PROJECT_LIST_FETCH_FAILED = 'PROJECT_LIST_FETCH_FAILED';

export const PROJECT_LIST_ITEM_SELECTE = 'PROJECT_LIST_ITEM_SELECTE';

export const TAG_LIST_FETCH_REQUESTED = 'TAG_LIST_FETCH_REQUESTED';
export const TAG_LIST_FETCH_SUCCEEDED = 'TAG_LIST_FETCH_SUCCEEDED';
