export const PROJECT_LIST_FETCH_REQUESTED = 'PROJECT_LIST_FETCH_REQUESTED';
export const PROJECT_LIST_FETCH_SUCCEEDED = 'PROJECT_LIST_FETCH_SUCCEEDED';
export const PROJECT_LIST_FETCH_FAILED = 'PROJECT_LIST_FETCH_FAILED';

export const PROJECT_FETCH_SUCCEEDED = 'PROJECT_FETCH_SUCCEEDED';
